apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ei93iu0lg-python 
  janus-idp.io/tekton: ei93iu0lg-python
  backstage.io/kubernetes-id: ei93iu0lg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ei93iu0lg-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml